defaults: &defaults
  host: staff.mongohq.com
  port: 10096
  username: heroku
  password: godpowers24

development:
  <<: *defaults
  database: app4067695

test:
  <<: *defaults
  database: app4067695

# set these environment variables on your prod server
production:
  <<: *defaults
  database: app4067695

